
/** 
 * The HtmlTags enum represents HTML tag names as integers so that
 * XPaths can be a list of ints rather than bloated strings.
 */
enum HtmlTags {
    ..         = 0,      // .. Move back up to parent in the XPath. This is a special entry in the enum and not an HTML tag
    comment    = 1,      // <!--...comment...--> Defines a comment
    DOCTYPE    = 2,      // <!DOCTYPE> Defines the document type
    a          = 3,      // <a> Defines a hyperlink
    abbr       = 4,      // <abbr> Defines an abbreviation or an acronym
    acronym    = 5,      // <acronym> Not supported in HTML5. Use <abbr> instead. Defines an acronym
    address    = 6,      // <address> Defines contact information for the author/owner of a document
    applet     = 7,      // <applet> Not supported in HTML5. Use <embed> or <object> instead. Defines an embedded applet
    area       = 8,      // <area> Defines an area inside an image-map
    article    = 9,      // <article> Defines an article
    aside      = 10,     // <aside> Defines content aside from the page content
    audio      = 11,     // <audio> Defines sound content
    b          = 12,     // <b> Defines bold text
    base       = 13,     // <base> Specifies the base URL/target for all relative URLs in a document
    basefont   = 14,     // <basefont> Not supported in HTML5. Use CSS instead. Specifies a default color, size, and font for all text in a document
    bdi        = 15,     // <bdi> Isolates a part of text that might be formatted in a different direction from other text outside it
    bdo        = 16,     // <bdo> Overrides the current text direction
    big        = 17,     // <big> Not supported in HTML5. Use CSS instead. Defines big text
    blockquote = 18,     // <blockquote> Defines a section that is quoted from another source
    body       = 19,     // <body> Defines the document's body
    br         = 20,     // <br> Defines a single line break
    button     = 21,     // <button> Defines a clickable button
    canvas     = 22,     // <canvas> Used to draw graphics, on the fly, via scripting (usually JavaScript)
    caption    = 23,     // <caption> Defines a table caption
    center     = 24,     // <center> Not supported in HTML5. Use CSS instead. Defines centered text
    cite       = 25,     // <cite> Defines the title of a work
    code       = 26,     // <code> Defines a piece of computer code
    col        = 27,     // <col> Specifies column properties for each column within a <colgroup> element 
    colgroup   = 28,     // <colgroup> Specifies a group of one or more columns in a table for formatting
    datalist   = 29,     // <datalist> Specifies a list of pre-defined options for input controls
    dd         = 30,     // <dd> Defines a description/value of a term in a description list
    del        = 31,     // <del> Defines text that has been deleted from a document
    details    = 32,     // <details> Defines additional details that the user can view or hide
    dfn        = 33,     // <dfn> Represents the defining instance of a term
    dialog     = 34,     // <dialog> Defines a dialog box or window
    dir        = 35,     // <dir> Not supported in HTML5. Use <ul> instead. Defines a directory list
    div        = 36,     // <div> Defines a section in a document
    dl         = 37,     // <dl> Defines a description list
    dt         = 38,     // <dt> Defines a term/name in a description list
    em         = 39,     // <em> Defines emphasized text 
    embed      = 40,     // <embed> Defines a container for an external (non-HTML) application
    fieldset   = 41,     // <fieldset> Groups related elements in a form
    figcaption = 42,     // <figcaption> Defines a caption for a <figure> element
    figure     = 43,     // <figure> Specifies self-contained content
    font       = 44,     // <font> Not supported in HTML5. Use CSS instead. Defines font, color, and size for text
    footer     = 45,     // <footer> Defines a footer for a document or section
    form       = 46,     // <form> Defines an HTML form for user input
    frame      = 47,     // <frame> Not supported in HTML5. Defines a window (a frame) in a frameset
    frameset   = 48,     // <frameset> Not supported in HTML5. Defines a set of frames
    h          = 49,     // <h1> to <h6>  Defines HTML headings
    head       = 50,     // <head> Defines information about the document
    header     = 51,     // <header> Defines a header for a document or section
    hr         = 52,     // <hr> Defines a thematic change in the content
    html       = 53,     // <html> Defines the root of an HTML document
    i          = 54,     // <i> Defines a part of text in an alternate voice or mood
    iframe     = 55,     // <iframe> Defines an inline frame
    img        = 56,     // <img> Defines an image
    input      = 57,     // <input> Defines an input control
    ins        = 58,     // <ins> Defines a text that has been inserted into a document
    kbd        = 59,     // <kbd> Defines keyboard input
    keygen     = 60,     // <keygen> Defines a key-pair generator field (for forms)
    label      = 61,     // <label> Defines a label for an <input> element
    legend     = 62,     // <legend> Defines a caption for a <fieldset> element
    li         = 63,     // <li> Defines a list item
    link       = 64,     // <link> Defines the relationship between a document and an external resource (most used to link to style sheets)
    main       = 65,     // <main> Specifies the main content of a document
    map        = 66,     // <map> Defines a client-side image-map
    mark       = 67,     // <mark> Defines marked/highlighted text
    menu       = 68,     // <menu> Defines a list/menu of commands
    menuitem   = 69,     // <menuitem> Defines a command/menu item that the user can invoke from a popup menu
    meta       = 70,     // <meta> Defines metadata about an HTML document
    meter      = 71,     // <meter> Defines a scalar measurement within a known range (a gauge)
    nav        = 72,     // <nav> Defines navigation links
    noframes   = 73,     // <noframes> Not supported in HTML5. Defines an alternate content for users that do not support frames
    noscript   = 74,     // <noscript> Defines an alternate content for users that do not support client-side scripts
    object     = 75,     // <object> Defines an embedded object
    ol         = 76,     // <ol> Defines an ordered list
    optgroup   = 77,     // <optgroup> Defines a group of related options in a drop-down list
    option     = 78,     // <option> Defines an option in a drop-down list
    output     = 79,     // <output> Defines the result of a calculation
    p          = 80,     // <p> Defines a paragraph
    param      = 81,     // <param> Defines a parameter for an object
    pre        = 82,     // <pre> Defines preformatted text
    progress   = 83,     // <progress> Represents the progress of a task
    q          = 84,     // <q> Defines a short quotation
    rp         = 85,     // <rp> Defines what to show in browsers that do not support ruby annotations
    rt         = 86,     // <rt> Defines an explanation/pronunciation of characters (for East Asian typography)
    ruby       = 87,     // <ruby> Defines a ruby annotation (for East Asian typography)
    s          = 88,     // <s> Defines text that is no longer correct
    samp       = 89,     // <samp> Defines sample output from a computer program
    script     = 90,     // <script> Defines a client-side script
    section    = 91,     // <section> Defines a section in a document
    select     = 92,     // <select> Defines a drop-down list
    small      = 93,     // <small> Defines smaller text
    source     = 94,     // <source> Defines multiple media resources for media elements (<video> and <audio>)
    span       = 95,     // <span> Defines a section in a document
    strike     = 96,     // <strike> Not supported in HTML5. Use <del> or <s> instead. Defines strikethrough text
    strong     = 97,     // <strong> Defines important text
    style      = 98,     // <style> Defines style information for a document
    sub        = 99,     // <sub> Defines subscripted text
    summary    = 100,    // <summary> Defines a visible heading for a <details> element
    sup        = 101,    // <sup> Defines superscripted text
    table      = 102,    // <table> Defines a table
    tbody      = 103,    // <tbody> Groups the body content in a table
    td         = 104,    // <td> Defines a cell in a table
    textarea   = 105,    // <textarea> Defines a multiline input control (text area)
    tfoot      = 106,    // <tfoot> Groups the footer content in a table
    th         = 107,    // <th> Defines a header cell in a table
    thead      = 108,    // <thead> Groups the header content in a table
    time       = 109,    // <time> Defines a date/time
    title      = 110,    // <title> Defines a title for the document
    tr         = 111,    // <tr> Defines a row in a table
    track      = 112,    // <track> Defines text tracks for media elements (<video> and <audio>)
    tt         = 113,    // <tt> Not supported in HTML5. Use CSS instead. Defines teletype text
    u          = 114,    // <u> Defines text that should be stylistically different from normal text
    ul         = 115,    // <ul> Defines an unordered list
    var        = 116,    // <var> Defines a variable
    video      = 117,    // <video> Defines a video or movie
    wbr        = 118,    // <wbr> Defines a possible line-break
}
